<link href="./css/cnkimdl.css" rel="stylesheet" type="text/css" />
<script language="JavaScript" type="text/javascript" src="./js/jquery-1.9.1.min.js"></script>
<script language="JavaScript" type="text/javascript" src="./js/Common.js"></script>
<script language="JavaScript" type="text/javascript" src="./js/adaptive.js"></script>
<script language="JavaScript" type="text/javascript" src="./js/mdl.js"></script>
